apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-portfolio-config
  labels:
    app: devops-portfolio
data:
  NODE_ENV: "production"
  PORT: "3000"
  APP_NAME: "DevOps - HeyPico.ai"
  APP_VERSION: "1.0.0"
  # Database configuration (example)
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "portfolio_db"
  # Monitoring configuration
  METRICS_ENABLED: "true"
  LOG_LEVEL: "info"
  # Feature flags
  HEALTH_CHECK_ENABLED: "true"
  PROMETHEUS_METRICS: "true"
