apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-nodeport
  labels:
    app: devops-portfolio
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: devops-portfolio
